---
- name: Check if apt key file exists
  stat:
    path: /usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg
  register: file_exists

- name: Add makedeb apt key.
  get_url:
    url: "{{ makedeb_apt_gpg_key }}"
    dest: /usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg
  when: not file_exists.stat.exists

- name: Add makedeb repository.
  apt_repository:
    repo: "{{ makedeb_apt_repository }}"
    state: present
    update_cache: true

- name: Install packages
  ansible.builtin.package:
    name: "{{ makedeb_packages }}"
    state: latest
